package com.ridestats.backend.service;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

import com.ridestats.backend.dto.SummaryPeriod;
import com.ridestats.backend.dto.SummaryStatsResponse;

class SummaryGeneratorServiceImplTest {

    private final SummaryGeneratorServiceImpl summaryGeneratorService = new SummaryGeneratorServiceImpl();

    @Test
    void generateFormatsFourWeekSummaryText() {
        SummaryStatsResponse summaryStats = new SummaryStatsResponse(
                12,
                560.0,
                76.7,
                101220,
                1479,
                19.9);

        String result = summaryGeneratorService.generate(summaryStats, SummaryPeriod.FOUR_WEEKS);

        assertEquals(String.join("\n",
                "FOUR WEEK SUMMARY",
                "",
                "Completed: 12 rides",
                "Total Distance: 560.0 km",
                "Longest: 76.7 km",
                "Avg. Speed: 19.9 kph",
                "Total Time: 28h 07m",
                "Total Climb: 1,479 m",
                "",
                "Generated by RideStats"), result);
    }

    @Test
    void generateFormatsMonthlySummaryText() {
        SummaryStatsResponse summaryStats = new SummaryStatsResponse(
                5,
                120.0,
                40.0,
                18000,
                800,
                24.0);

        String result = summaryGeneratorService.generate(summaryStats, SummaryPeriod.MONTHLY);

        assertEquals("MONTHLY SUMMARY", result.lines().findFirst().orElseThrow());
    }

    @Test
    void generateFormatsYearlySummaryText() {
        SummaryStatsResponse summaryStats = new SummaryStatsResponse(
                50,
                2500.0,
                100.0,
                500000,
                25000,
                18.0);

        String result = summaryGeneratorService.generate(summaryStats, SummaryPeriod.YEARLY);

        assertEquals("YEARLY SUMMARY", result.lines().findFirst().orElseThrow());
    }
}
