package com.ridestats.backend.service;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

import com.ridestats.backend.dto.SummaryStats;

class SummaryGeneratorServiceImplTest {

    private final SummaryGeneratorServiceImpl summaryGeneratorService = new SummaryGeneratorServiceImpl();

    @Test
    void generateFormatsSummaryText() {
        SummaryStats summaryStats = new SummaryStats(
                12,
                560.0,
                76.7,
                101220,
                1479,
                19.9);

        String result = summaryGeneratorService.generate(summaryStats);

        assertEquals(String.join("\n",
                "FOUR WEEK SUMMARY",
                "",
                "Completed: 12 rides",
                "Total Distance: 560.0 km",
                "Longest: 76.7 km",
                "Avg Speed: 19.9 kph",
                "Total Time: 28h 07m",
                "Total Climb: 1,479 m",
                "",
                "Generated by RideStats"), result);
    }
}