spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.application.name=RideStats
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.security.user.name=ridestats
spring.security.user.password=ridestats123
spring.datasource.url=jdbc:postgresql://localhost:5432/ridestats
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true