package com.ridestats.backend.service;

import java.util.Locale;

import org.springframework.stereotype.Service;

import com.ridestats.backend.dto.SummaryStats;

/**
 * Default implementation for generating summary text.
 */
@Service
public class SummaryGeneratorServiceImpl implements SummaryGeneratorService {

    @Override
    public String generate(SummaryStats summaryStats) {
        return String.join("\n",
                "FOUR WEEK SUMMARY",
                "",
                String.format(Locale.US, "Completed: %d rides", summaryStats.completedRides()),
                String.format(Locale.US, "Total Distance: %.1f km", summaryStats.totalDistanceKm()),
                String.format(Locale.US, "Longest: %.1f km", summaryStats.longestRideKm()),
                String.format(Locale.US, "Avg Speed: %.1f kph", summaryStats.averageSpeedKph()),
                String.format(Locale.US, "Total Time: %s", formatDuration(summaryStats.totalTimeSeconds())),
                String.format(Locale.US, "Total Climb: %,d m", Math.round(summaryStats.totalClimbM())),
                "",
                "Generated by RideStats");
    }

    private static String formatDuration(long totalSeconds) {
        long hours = totalSeconds / 3600;
        long minutes = (totalSeconds % 3600) / 60;
        return String.format(Locale.US, "%dh %02dm", hours, minutes);
    }
}