package com.ridestats.backend.service;

import java.util.Locale;

import org.springframework.stereotype.Service;

import com.ridestats.backend.dto.SummaryPeriod;
import com.ridestats.backend.dto.SummaryStatsResponse;
import com.ridestats.backend.util.DurationFormatter;

/**
 * Default implementation for generating summary text.
 */
@Service
public class SummaryGeneratorServiceImpl implements SummaryGeneratorService {

    @Override
    public String generate(SummaryStatsResponse summaryStats, SummaryPeriod period) {
        return String.join("\n",
                period.title(),
                "",
                String.format(Locale.US, "Completed: %d rides", summaryStats.completedRides()),
                String.format(Locale.US, "Total Distance: %.1f km", summaryStats.totalDistanceKm()),
                String.format(Locale.US, "Longest: %.1f km", summaryStats.longestRideKm()),
                String.format(Locale.US, "Avg. Speed: %.1f kph", summaryStats.averageSpeedKph()),
                String.format(Locale.US, "Total Time: %s", DurationFormatter.format(summaryStats.totalTimeSeconds())),
                String.format(Locale.US, "Total Climb: %,d m", Math.round(summaryStats.totalClimbM())),
                "",
                "Generated by RideStats");
    }
}
